### PR TITLE
daemon/containerd: fix compat for "docker run" with image that's not present

### PR DESCRIPTION
**Pull request by thaJeztah**
It's horrible, but some clients (such as the docker 17.03 CLI used in CI) still perform string-matching to detect that the *image* wasn't found. This requires the error to be prefixed with "No such image:". Without this prefix, the CLI prints the error message, and exits.

Before this:

    docker run -it --rm hello-world
    docker: Error response from daemon: id not found.
    See 'docker run --help'.

After this:

    docker run -it --rm hello-world
    Unable to find image 'hello-world:latest' locally
    faa03e786c97: Download complete
    ...

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by rumpl — APPROVED** [review]

**Comment by thaJeztah** [comment]
```
github.com/containerd/containerd/vendor/github.com/miekg/pkcs11
#50 293.6 cgo: malformed DWARF TagVariable entry
```

Looks like we need https://github.com/moby/moby/pull/44571

**Comment by thaJeztah** [comment]
opened https://github.com/rumpl/moby/pull/123 to fix CI

**Comment by thaJeztah** [comment]
Rebased after https://github.com/rumpl/moby/pull/123 was merged; CI should (hopefully) go green now 👍

**Comment by thaJeztah** [comment]
All green 🎉 bringing this one in 👍

**Comment by thaJeztah** [comment]
This should be upstreamed together with

- https://github.com/rumpl/moby/pull/88
- https://github.com/rumpl/moby/pull/8

**Pull request merged**
